### ISSUE TITLE
No errors.

### ISSUE THREAD

**Issue by mattn** [google/gxui#1]
I built gxui on windows. It works fine without one thing. I must apply small patch to go-gl-legacy.

https://gist.github.com/mattn/827bc949adf45e9e4df5

There seems to be some versions which returns `No errors.` from glGetProgramInfoLog/glGetShaderInfoLog.
So I suggues that ignore `No errors.` at below:

https://github.com/google/gxui/blob/7375707d215187777376037e507809436dff3f19/drivers/gl/shader_program.go#L26
https://github.com/google/gxui/blob/7375707d215187777376037e507809436dff3f19/drivers/gl/shader_program.go#L43

If you are okay, I'll send PR to you.

**additional comment**
Or remove checking

**Comment by ben-clayton** [comment]
Hi mattn,
Blimey, that was quick - GXUI has only been public for about about 18 hours. I was hoping for a quiet launch so I had time to tidy the source. :)

The COMPILE_STATUS test looks like the correct solution. Is this enough to fix your problem?
It appears you have signed Google's Contribution License Agreement. Is this correct?

**Comment by mattn** [comment]
> The COMPILE_STATUS test looks like the correct solution. Is this enough to fix your problem?

COMPILE_STATUS is not work well for this case. Because if COMPILE_STATSUS become GL_TRUE, the log returns `No errors.`. So checking COMPILE_STATUS is not good for me.
About my commits in above, since first commit is wrong, I forcely pushed second commit. So if you click `merge` button, the second one will be merged. Please notice.

> It appears you have signed Google's Contribution License Agreement. Is this correct?

Yes, I had already signed CLA for golang/go.

**Comment by ben-clayton** [comment]
>> Because even though COMPILE_STATSUS become GL_FALSE, the log returns No errors.

Right - I think the problem is that you're checking COMPILE_STATUS for both the shader and the program.
You probably want:

    s.Compile()
    if s.Get(gl.COMPILE_STATUS) != gl.TRUE {
        panic(s.GetInfoLog())
    }

and:

    program.Link()
    program.Validate()
    if program.Get(gl.LINK_STATUS) != gl.TRUE {
        panic(program.GetInfoLog())
    }

Do you mind seeing if making these changes fixes your issue?

>> Yes, I had already signed CLA for golang/go.

Great.

**Comment by mattn** [comment]
done.

**Comment by mattn** [comment]
Ah, it's better to be PR.
