### ISSUE TITLE
type MouseEvent: buttons are not handled

### ISSUE THREAD

**Issue by DoctorovEV** [google/gxui#106]
Ben, good Health!

How to determine which mouse button is pressed in event OnMouseMove?

**Comment by ben-clayton** [comment]
Hi @DoctorovEV,
Currently you cannot.
If you want this, then:
* The [MouseButton](https://github.com/google/gxui/blob/master/mouse_button.go#L10) enum should become a ```MouseButtonState``` bitfield, and should have the following methods added:
```go
func (s MouseButtonState) IsLeftDown() bool { ... }
func (s MouseButtonState) IsMiddleDown() bool { ... }
func (s MouseButtonState) IsRightDown() bool { ... }
```
* [MouseEvent.Button](https://github.com/google/gxui/blob/master/mouse_event.go#L12) should be renamed to ```ButtonState```.
* All the places where a ```MouseEvent``` is created in [viewport.go](https://github.com/google/gxui/blob/master/drivers/gl/viewport.go#L120) should be updated to assign the ```ButtonState``` field.
* All the existing code that checks for [button equality](https://github.com/google/gxui/blob/master/mixins/button.go#L97) would have to be updated to use the ```IsLeftDown()``` / ```IsMiddleDown()``` / ```IsRightDown()``` methods instead.


I can do this, but I'm exceptionally busy this week. I'm happy to review a pull-request if you're comfortable doing this yourself.

Cheers,
Ben

**Comment by DoctorovEV** [comment]
Thank you, Ben. I'll wait for the official implementation of the next week.

**Comment by ben-clayton** [comment]
@yofu has done the hard work on this. Please reopen if this doesn't give you what you need.
