### ISSUE TITLE
I propose the morphic ui concept for the architecture of gxui, being very unixy in it's fundamental behaviour

### ISSUE THREAD

**Issue by brancoliticus** [google/gxui#115]
Morphic originates in the Self language as a simple paradigm for bringing the Smalltalk paradigm as envisioned by Allen Kay and others, including Dan Ingalls, to the user interface. The nice thing about Morphic and Smalltalk is that they are very similar to the unix model of pipes and files and files that are executables, and also to the plan9 model where everything is a file accesable simply  through the files interface functions, including ethernet, processes and so on.

Dan Ingalls and his various collaborators have reimplemented the Morphic concept in LivelyKernel in javascript while being at Sun Labs, and continued work on the project while at Hasso-Plattner-Institute, with the result being a usable system that was demoed in the GoogleTechTalk recorded at https://www.youtube.com/watch?v=gGw09RZjQf8. After seing the presentation I believe that one has an understanding that what is in the LivelyKernel code base is the correct minimal way to assemble user interfaces in a way that is compatible with the unix model of small tools that composable functionality.

One issue with the LivelyKernel is that it has no knowledge of access control, the stuff that is implemented in unix with the concept of users and groups and their access rights to files, so you cannot for example create interactively a nice ui in your LivelyKernel playground and ship it to an end user filling a form to login to google mail or their online bank account, because you would be basically shipping the codebase and the IDE along with the desired end user functionality. That would not preclude engineers at Google to embed rule based access control unix style into a transplantation of the LivelyKernel user interface architecture to the go platform.

Now time for some glowing vision of things that might be: the developer builds the ui in a Morphic/LivelyKernel style, he is in the developer group but grants read access to the anonymous group to the login form in it's entirety, grants write access to the login form input boxes, presses a button to ship the form to the server, the server cuts out reading and editing functionality from the form for the anonymous group that is anyone on the internet, all according to the users and groups rights that were determined by the developer, and starts shipping the form to anyone on the internet making a request to the server, which will all receive access to the anonymous group.

**Comment by ben-clayton** [comment]
While I appreciate discussions on the pros and cons of UI and framework design, there is very little in what you have written that I can act upon.
If you have suggestions on how Morphic or LivelyKernel's approach could benefit GXUI, please suggest away, or feel free to fork GXUI and try out these ideas. I'm always happy to accept pull requests that improve the code.
