### ISSUE TITLE
SetHorizontalAlignment(gxui.AlignRight) ?

### ISSUE THREAD

**Issue by Daedfr** [google/gxui#116]
label := theme.CreateLabel()
	label.SetFont(font)
	label.SetText("Hello world")
	label.SetHorizontalAlignment(gxui.AlignRight)
	label.OnClick(func(gxui.MouseEvent) {
		fmt.Printf("test")
	})

The label stay on left , maybe i don't understand something ?

**Comment by ben-clayton** [comment]
Hi @Daedfr,
A label's alignment is mostly used for multi-line text. If you'd like a label to be right aligned in the parent container, consider parenting label under a [LinearLayout](https://github.com/google/gxui/blob/master/linear_layout.go) with the layout's [HorizontalAlignment](https://github.com/google/gxui/blob/master/linear_layout.go#L37) set to [AlignRight](https://github.com/google/gxui/blob/master/alignment.go#L12) and its [SizeMode](https://github.com/google/gxui/blob/master/linear_layout.go#L29) set to [Fill](https://github.com/google/gxui/blob/master/size_mode.go#L11).

I hope this helps,
Ben
