### ISSUE TITLE
Error running image_viewer in samples folder

### ISSUE THREAD

**Issue by tinycedar** [google/gxui#12]
Error running image_viewer in samples folder:
![1](https://cloud.githubusercontent.com/assets/8019222/6713357/b42008d4-cdcc-11e4-922d-7e47412acdea.png)

And I have OpenGL support as snapshot shows blow:
![capture](https://cloud.githubusercontent.com/assets/8019222/6713404/f9cbff50-cdcc-11e4-86bc-6f9701e81550.PNG)

**Comment by ben-clayton** [comment]
Hi @tinycedar - that's unfortunate. The hardware specs seem unusual - is this a tablet? It's very odd to find a driver that supports shader model 4, but only GL 1.1.
Unless you're able to update the drivers to a version that supports a more recent OpenGL API, I'm afraid there's little I can do to help for now. I suppose someone _could_ write a Direct3D driver...

**Comment by crawshaw** [comment]
FYI, my long-term plan for golang.org/x/mobile/app support on windows is https://code.google.com/p/angleproject/. You may want to track golang/go#9306.

**Comment by ben-clayton** [comment]
I'm afraid there's little we can do to help at the moment. Maybe in the future we can implement alternative drivers or use angle like @crawshaw suggests. Closing for now.

**Comment by linquize** [comment]
![openglversion](https://cloud.githubusercontent.com/assets/791115/6734962/1e6a8600-ce96-11e4-9b31-64ac20969929.png)

Is this version OK? I got black screen.
I run `image_viewer --file path\to\image.png`

**Comment by crawshaw** [comment]
Driver looks fine. The sample program will not display png/jpeg/etc images until https://github.com/google/gxui/pull/19 is applied.
