### ISSUE TITLE
Multiline Label, Character Glitch

### ISSUE THREAD

**Issue by boljen** [google/gxui#124]
The first character seems glitched when working with multiline labels in that there's a small box around it (windows 8, pro). Am I doing something wrong or is this actually a bug?

        package main

        import (
                "github.com/google/gxui"
                "github.com/google/gxui/drivers/gl"
                "github.com/google/gxui/themes/dark"
                "github.com/google/gxui/gxfont"
        )

        func main() {
                gl.StartDriver(initApp)
        }

        func initApp(driver gxui.Driver) {
                theme := dark.CreateTheme(driver);
                font, err := driver.CreateFont(gxfont.Default, 20)
                if err != nil || font == nil {
                        panic(err)
                }

                window := theme.CreateWindow(300, 300, "Test");
                label := theme.CreateLabel()
                label.SetMultiline(true)
                label.SetText("line 1\nline 2")
                label.SetColor(gxui.White)
                label.SetFont(font)
                window.AddChild(label)

                window.OnClose(driver.Terminate)
        }

**Comment by ben-clayton** [comment]
It was almost certainly a carriage return character being rendered (which doesn't have a glyph). Thanks to @dskinner for the very rapid fix.
