### ISSUE TITLE
Error Building `image_viewer` Sample

### ISSUE THREAD

**Issue by dc0d** [google/gxui#14]
Executing command `go build main.go` in `image_viewer` folder on Windows 8, go 1.4.2 x86 gives this error:

C:\...\image_viewer>go build main.go
..\..\drivers\gl\glyph_page.go:13:2: cannot find package "code.google.com/p/freetype-go/freetype/raster" in any of:
        C:\devox-apps\go\src\code.google.com\p\freetype-go\freetype\raster (from $GOROOT)
        C:\Workshop\Devox\Workshop-Go\src\code.google.com\p\freetype-go\freetype\raster (from $GOPATH)
..\..\drivers\gl\font.go:14:2: cannot find package "code.google.com/p/freetype-go/freetype/truetype" in any of:
        C:\devox-apps\go\src\code.google.com\p\freetype-go\freetype\truetype (from $GOROOT)
        C:\Workshop\Devox\Workshop-Go\src\code.google.com\p\freetype-go\freetype\truetype (from $GOPATH)
..\..\drivers\gl\blitter.go:11:2: cannot find package "github.com/go-gl/gl/v3.2-core/gl" in any of:
        C:\devox-apps\go\src\github.com\go-gl\gl\v3.2-core\gl (from $GOROOT)
        C:\Workshop\Devox\Workshop-Go\src\github.com\go-gl\gl\v3.2-core\gl (from $GOPATH)
..\..\drivers\gl\driver.go:15:2: cannot find package "github.com/go-gl/glfw/v3.1/glfw" in any of:
        C:\devox-apps\go\src\github.com\go-gl\glfw\v3.1\glfw (from $GOROOT)
        C:\Workshop\Devox\Workshop-Go\src\github.com\go-gl\glfw\v3.1\glfw (from$GOPATH)

**Comment by dc0d** [comment]
Crap; half of story was my fault. I had not `hg` in command line. Still the other half is "code.google.com/p/freetype-go/freetype/raster" does not exists.

**Comment by ben-clayton** [comment]
Please try running:
`go get code.google.com/p/freetype-go/freetype/raster`
To explicitly fetch that project. I also noticed that automatic dependency fetching was a little flaky on windows earlier today.

**Comment by dc0d** [comment]
Thanks; still no lock. Maybe this should wait until transition to GitHub gets completed(?) and packages be used with new paths - if so, this would work fine on Windows.

**Comment by crawshaw** [comment]
You can also
    hg clone https://code.google.com/p/freetype-go
into your GOPATH.

**Comment by ryanseys** [comment]
I ran `go get code.google.com/p/freetype-go/freetype` and it worked for me.

**Comment by ben-clayton** [comment]
Sorry - that's what I should have said in the first place.
Glad it's now working for you. I've updated the readme to include the dependencies. Hopefully this should avoid this sort of frustration in the future.
Cheers.
