### ISSUE TITLE
Please export freetype-go to github

### ISSUE THREAD

**Issue by vzever** [google/gxui#150]
Google Code will be turning read-only on August 25th. Would you  export freetype-go to github , and change "code.google.com/p/freetype-go"  to  "github.com/*/freetype-go" ?

**Comment by ben-clayton** [comment]
I've raised this with @nigeltao, who is one of the primary contributors to freetype-go.

**Comment by vzever** [comment]
Now we can use "import github.com/golang/freetype" instead of "import code.google.com/p/freetype-go".

**Comment by nigeltao** [comment]
Dont switch over to the github version just yet. I intend to make breaking API changes over the next week or three.

**Comment by nigeltao** [comment]
golang-nuts post about the move to github.com/golang/freetype:
https://groups.google.com/d/topic/golang-nuts/tr-MftD7kbo/discussion
