### ISSUE TITLE
Resizing grid layout

### ISSUE THREAD

**Issue by Mr4x** [google/gxui#151]
The initial size of `cell` is `{0 0}`, then I change it to `{200 200}`, but visually nothing changes. As a result I want to get a table divided into 16 squares.

    grid := theme.CreateLinearLayout()
    grid.SetDirection(gxui.LeftToRight)

    for x := 0; x < 4; x++ {
        column := theme.CreateLinearLayout()
        column.SetDirection(gxui.TopToBottom)
        for y := 0; y < 4; y++ {
            cell := theme.CreateLinearLayout()
            cell.SetSize(math.Size{200, 200})

            text := theme.CreateLabel()
            text.SetText(fmt.Sprintf("%d", x*4+y))

            cell.AddChild(text)
            column.AddChild(cell)
        }
        grid.AddChild(column)
    }

    window.AddChild(grid)

![screen shot 2015-08-13 at 12 48 27 am](https://cloud.githubusercontent.com/assets/8566102/9234881/0da86b5c-4155-11e5-81d3-2b3e972e6ccd.png)

**Comment by ben-clayton** [comment]
[SetSize](https://github.com/google/gxui/blob/master/control.go#L15) is not to be used by the application code - it is an internal function used by containers only during layout passes.
I'm afraid there is no such grid container currently implemented and has [been requested](https://github.com/google/gxui/issues/103). I'll bump this in my TODO priority list, but I'm afraid I'm getting little time to work on GXUI lately. If anyone is feeling brave, I'd happily accept a pull request.
