### ISSUE TITLE
question  freetype didn't findit

### ISSUE THREAD

**Issue by 7belrhalmia** [google/gxui#155]
cannot find package   "code.google.com/p/freetype-go/freetype/truetype" in any of:
         /usr/lib/go/src/pkg/code.google.com/p/freetype-go/freetype/truetype (from $GOROOT)
          /home/belr/Goprogram/vendor/src/code.google.com/p/freetype-go/freetype/truetype (from $GOPATH)
        /home/belr/Goprogram/src/code.google.com/p/freetype-go/freetype/truetype

**Comment by shurcooL** [comment]
I can reproduce with `go version go1.5 darwin/amd64`:

```bash
~ $ export GOPATH=/tmp/empty_fresh_workspace
~ $ go get -u github.com/google/gxui/...
package github.com/google/gxui/drivers/gl
	imports code.google.com/p/freetype-go/freetype/raster: unable to detect version control system for code.google.com/ path
package github.com/google/gxui/drivers/gl
	imports code.google.com/p/freetype-go/freetype/truetype: unable to detect version control system for code.google.com/ path
~ $ echo $?
1
~ $ ls $GOPATH/src
github.com	golang.org
~ $ 
```

code.google.com is being sunset before its upcoming shutdown, and this seems to be related. That repo has moved to https://github.com/golang/freetype so code.google.com redirects, and that prevents `go get` from working.

The fix is for `gxui` to update to use the new `github.com/golang/freetype` import path.

**Comment by shurcooL** [comment]
@7belrhalmia, as a temporary workaround until import paths are updated so it's go-gettable again, you can manually `hg clone` the old repository:

```bash
$ mkdir -p $GOPATH/src/code.google.com/p
$ cd $GOPATH/src/code.google.com/p
$ hg clone https://code.google.com/p/freetype-go
...
destination directory: freetype-go
requesting all changes
adding changesets
adding manifests
adding file changes
added 129 changesets with 385 changes to 52 files
updating to branch default
38 files updated, 0 files merged, 0 files removed, 0 files unresolved
```

That will then allow `go install github.com/google/gxui/...` to succeed.

**Comment by shurcooL** [comment]
See https://github.com/google/gxui/issues/150#issuecomment-135656424.
