### ISSUE TITLE
Table cols and rows are reversed.

### ISSUE THREAD

**Issue by danmondy** [google/gxui#160]
Comments in table example say 
//rows, columns
SetGrid(3, 2)

Which would be three rows by two columns (taller than wide). However, that is not how it is treated.

I don't think the comment should be changed, but rather the inner workings as it is normal to pass rows first, then cols.

**Comment by danmondy** [comment]
I would like to fix this myself since it is simple enough, but I've never contributed to anything before. I'm relatively new to git and I don't want to upset anyone. I created a new branch named 160 but I am not sure how to commit, or submit a pull request or where to go from here.

**Comment by shurcooL** [comment]
> as it is normal to pass rows first, then cols.

Where is that coming from?

I'm not against it, I'd just like to learn.

**Comment by danmondy** [comment]
I was mostly basing it on java swing which usually takes row, cols. Also the idea of x and y which are usually passed in that order (though one could argue that cols correlate to x more than rows.) If nothing else we can just change the comments in the samples, but it definitely misled me and then I didn't know if I could trust the SetChildAt orders as well.

**Comment by shurcooL** [comment]
Yep, it's clear there's an issue, it's just a matter of determining which way to fix it (update the comment to match current `SetGrid`, or the reverse as you've done in #162).

> I was mostly basing it on java swing which usually takes row, cols (new GridLayout(rows, cols)).

I see, thanks.

> Also the idea of x and y which are usually passed in that order (though one could argue that cols correlate to x more than rows.)

Yeah, if you compare to X and Y, I would say X, being the horizontal component, correlates to columns being first.

I'm sure @ben-clayton will know which is the best way to go here.

**Comment by dskinner** [comment]
A `3x2 grid` should intuitively mean `3 across` and `2 down`. I'd either update the comment or change the name of the func to be representative of passing `N rows` as the first argument.

The breakdown in language occurs mostly b/c, I would guess, people aren't column oriented. They are considering row length, and number of rows. Once you are column oriented in thought, things get weird.

In short, update the comment.

**Comment by shurcooL** [comment]
> A `3x2 grid` should intuitively mean `3 across` and `2 down`.

That makes the most sense to me.

> In short, update the comment.

Agreed. :+1:

**Comment by ben-clayton** [comment]
Sounds good to me. Obviously we should also be documenting the interface too. :)
