### ISSUE TITLE
Panics on integrated graphics card.

### ISSUE THREAD

**Issue by jkbbwr** [google/gxui#20]
When running on a machine with an integrated graphics card, I get the following panic.

I don't intend to install nvidia graphics yet, I was hoping to be able to run it on the intel integrated card.
```
Xlib:  extension "GLX" missing on display ":0".
Xlib:  extension "GLX" missing on display ":0".
panic: APIUnavailable: GLX: GLX extension not found

goroutine 1 [running, locked to thread]:
github.com/google/gxui/drivers/gl.StartDriver(0x0, 0x0, 0x90cf10)
	/home/jakob/tmp/src/github.com/google/gxui/drivers/gl/driver.go:41 +0x87
main.main()
	/home/jakob/tmp/src/github.com/google/gxui/samples/lists/main.go:152 +0x48

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
```

**Comment by crawshaw** [comment]
You'll need to install the appropriate OpenGL drivers. How to do that depends on the kind of hardware you have and on the linux you are using. Try doing a google search for "<name of your distro> <brand of your graphics card> install opengl".

**Comment by dskinner** [comment]
Does it make sense to support non-accelerated rendering where possible? For example, mesa on linux and LIBGL_ALWAYS_SOFTWARE env flag.

Or is it more suitable to expect such a thing to be configured at the OS level?

**Comment by crawshaw** [comment]
A software version of modern OpenGL should be able to support the current driver. But it's also unusual to run into graphics cards that do not support modern gl.
