### ISSUE TITLE
list item reuse?

### ISSUE THREAD

**Issue by dskinner** [google/gxui#26]
I tried giving the code a quick look over, specifically `mixings/list.go` and it looks like item controls are recreated during scroll so that a list of 10,000 items of the same control would end up creating 10,000 unique controls over the course of scrolling while only keeping the visible ones in memory (so lots of garbage).

Did I read this right? Instead of simply deleting the old control tied to a given item id, it should be reused to reduce the amount of garbage. This also implies a create + bind phase for adapter implementations instead of just a create phase.

Along those same lines since this would change storage of controls by their view type instead of adapter id, it'd be nice if adapter item ids weren't required to be unique.

Thanks!

**Comment by ben-clayton** [comment]
Hi Daniel,
If I understand you correctly, you are asking if the [List](https://github.com/google/gxui/blob/master/list.go) / [Adapter](https://github.com/google/gxui/blob/master/adapter.go) implementation has any form of control recycling. The answer is no, but if we find that this is a performance problem, I don't object to adding it - it would be trivial to add a Destroy method to [Adapter](https://github.com/google/gxui/blob/master/adapter.go) that complements the [Create](https://github.com/google/gxui/blob/master/adapter.go#L22).

I have however seen no real performance problems to suggest this is currently needed - the Go GC certainly seems fast enough for **very** large datasets on the machines I've tried. For example, one application we have has 250,000 items in a list, each with many sub-controls, and we can quite easily scroll through them without any noticeable stuttering.

I hope this answers your question.

**Comment by dskinner** [comment]
That 250K item list sounds great but I imagine there's a cap to the max garbage generated irregardless of actual adapter size and dependent on scroll speed. I am still concerned for more complex forms so will investigate the actual performance hit.

**Comment by ben-clayton** [comment]
Closing this for now.
Until we can prove the lack of recycling is an issue, I'm going to consider this WAI.
