### ISSUE TITLE
build github.com/go-gl/glfw/v3.1/glfw  error on win64

### ISSUE THREAD

**Issue by codeskyblue** [google/gxui#36]
go get github.com/go-gl/glfw/v3.1/glfw

**Comment by ben-clayton** [comment]
Care to elaborate?
What errors are you getting? 
What build environment have you set up?

**Comment by ben-clayton** [comment]
I cannot help you without additional information. If you are still having issues, please post more details and reopen.

**Comment by codeskyblue** [comment]
Issue better to close, build was success today. wired. sorry about the bad issue.
