### ISSUE TITLE
panic: APIUnavailable: GLX: GLX version 1.3 is required [Ubuntu]

### ISSUE THREAD

**Issue by anidotnet** [google/gxui#38]
While running any of the sample application, I am getting below error
```
GLFW: An uncaught error has occurred: PlatformError: X11: RandR gamma ramp support seems broken
GLFW: Please report this bug in the Go package immediately.
panic: APIUnavailable: GLX: GLX version 1.3 is required

goroutine 1 [running, locked to thread]:
github.com/google/gxui/drivers/gl.StartDriver(0x90ced0)
        /home/anindya/codebase/gopath/src/github.com/google/gxui/drivers/gl/driver.go:36 +0x87
main.main()
        /home/anindya/codebase/gopath/src/github.com/google/gxui/samples/lists/main.go:150 +0x2f

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        /home/anindya/Applications/go/src/runtime/asm_amd64.s:2232 +0x1
```
And here is the system details

Ubuntu 14.04.2 LTS - 64bit
OpenGL version string: 2.1 Mesa 10.1.3
go version go1.4.2 linux/amd64

**Comment by ben-clayton** [comment]
The ```X11: RandR gamma ramp support seems broken``` message appears to be coming from [glfw/x11_init.c](https://github.com/glfw/glfw/blob/master/src/x11_init.c#L525).
The preceding comment says:
```C 
// This is either a headless system or an older Nvidia binary driver
// with broken gamma support
```

Are you using an old NVIDIA driver?

**Comment by anidotnet** [comment]
I was running it in a remote x2go session.

**Comment by ben-clayton** [comment]
Okay, that's not something I would expect to work unless you somehow switch to a software renderer. Unless someone smarter than me can guide you on how to do this, I'm afraid there's little I can do to help here.

**Comment by snoury** [comment]
According to http://wiki.x2go.org/doku.php/doc:de-compat, x2go is based on nxagent which supports GLX up to 1.2 while GLFW requires GLX 1.3 (http://www.glfw.org/docs/latest/compat.html#compat_glx). Until x2go implements support for GLX 1.3 (http://wiki.x2go.org/doku.php/wiki:development:new-feature-brainstorming#nx-libs), it's unlikely that gxui will be supported in its current form on x2go, due to its dependency on GLFW.

**Comment by ben-clayton** [comment]
Good investigation skills, Sherlock Noury!
I'm afraid it looks like there's little we can do to help on this particular hardware. A software driver implementation would make it possible to use GXUI, but this is a long way off and would take some serious optimisation.
Closing for now.
