### ISSUE TITLE
Ubuntu 14.10 missing include files errors in go get github.com/go-gl/gl/v3.2-core/gl

### ISSUE THREAD

**Issue by haisum** [google/gxui#39]
While doing `go get github.com/go-gl/gl/v3.2-core/gl`  on Ubuntu I got error of missing GL/glx.h header file. After fixing include error, I got following error: 
```
/usr/bin/ld: cannot find -lGL
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
```

![selection_056](https://cloud.githubusercontent.com/assets/911409/6749335/057171ec-cf11-11e4-9827-4f0057f2e12a.png)

Fixed both errors by doing `sudo apt-get install mesa-common-dev libgl1-mesa-dev`.

Hope it helps someone else and documentation should be updated.

**Comment by ben-clayton** [comment]
Thank you @haisum, I've added these dependencies to the README.
