### ISSUE TITLE
Ubuntu 14.10 missing include files  errors in go get github.com/go-gl/glfw/v3.1/glfw

### ISSUE THREAD

**Issue by haisum** [google/gxui#40]
After finally getting `go get github.com/go-gl/gl/v3.2-core/gl` to work and solve issues mentioned in https://github.com/google/gxui/issues/39  `go get github.com/go-gl/glfw/v3.1/glfw` also popped up a few errors of missing following include files:

- X11/extensions/Xinerama.h
- X11/extensions/XInput2.h
- X11/Xcursor/Xcursor.h
- X11/extensions/Xrandr.h

These include files are available in packages `libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev` so installing them by doing `sudo apt-get install libxi-dev libxcursor-dev libxrandr-dev libxinerama-dev` fixed the errors. Updated documentation is needed.

**Comment by nguyendangminh** [comment]
Hi Hisum, I posted it in the wiki already: https://github.com/google/gxui/wiki/Installation

**Comment by haisum** [comment]
oh @nguyendangminh didn't notice the wiki. Nice work :) I was following readme.md may be Installation wiki should be linked from Readme.md?

**Comment by nguyendangminh** [comment]
Yes, it should be. I've just created the wiki today.

**Comment by ben-clayton** [comment]
Thank you for creating the Wiki - this is really helpful.
I will put the package dependencies on the README anyway as this seems to be a common problem.

**Comment by ben-clayton** [comment]
If this README gets unwieldy, then I'll point people to the installation wiki page instead.
Thanks for your help guys.
