### ISSUE TITLE
Can you port this to Dart?

### ISSUE THREAD

**Issue by Emasoft** [google/gxui#42]
This is a very cool library. Can you port this to Dart?

**Comment by crawshaw** [comment]
The design of GXUI is particular to Go and would not port well to another language.

Furthermore, Dart would be an unusual target for an OpenGL-based UI library. Typically Dart runs in web browsers with access to the DOM, a full-featured standardized cross platform UI library. Attempting to reinvent that in a browser would be an enormous effort.

**Comment by ben-clayton** [comment]
Thank you @Emasoft. I imagine it's possible with a lot of time, but we already have quite enough on our plate transforming GXUI into a usable library for Go.
I d
