### ISSUE TITLE
arm-linux-androideabi-gcc: error: unrecognized command line option '-m64'

### ISSUE THREAD

**Issue by oldfeel** [google/gxui#44]
````
oldfeel@oldfeel:~$ go get github.com/go-gl/gl/v3.2-core/gl
# github.com/go-gl/gl/v3.2-core/gl
arm-linux-androideabi-gcc: error: unrecognized command line option '-m64'
oldfeel@oldfeel:~$ go get github.com/go-gl/glfw/v3.1/glfw
# github.com/go-gl/glfw/v3.1/glfw
arm-linux-androideabi-gcc: error: unrecognized command line option '-m64'
````

by ubuntu 14.04 64

**Comment by crawshaw** [comment]
You are using a version of Go built with an android C compiler toolchain, but with a non-android GOOS value. You'll have to keep your android Go installation separate from your desktop installation.

Also: if you're trying to build GXUI for Android, it won't work yet. I hope to have support in a few weeks.
