### ISSUE TITLE
missing data/xyz.ttf resources

### ISSUE THREAD

**Issue by sbinet** [google/gxui#5]
hi,

trying to run the ``samples`` apps, I get:

```sh
$ go run ./progress_bar/main.go 
panic: open data/SourceCodePro-Regular.ttf: no such file or directory

goroutine 5 [running]:
github.com/google/gxui/drivers/gl.(*Driver).CreateFont(0xc20803a3c0, 0x75a1d0, 0x19, 0xc, 0x0, 0x0)
	/home/binet/tmp/go/src/github.com/google/gxui/drivers/gl/driver.go:166 +0x17d
github.com/google/gxui/themes/dark.CreateTheme(0x7f14ee8b2b40, 0xc20803a3c0, 0x0, 0x0)
	/home/binet/tmp/go/src/github.com/google/gxui/themes/dark/theme.go:43 +0x76
main.appMain(0x7f14ee8b2b40, 0xc20803a3c0)
	/home/binet/tmp/go/src/github.com/google/gxui/samples/progress_bar/main.go:19 +0x61
created by github.com/google/gxui/drivers/gl.StartDriver
	/home/binet/tmp/go/src/github.com/google/gxui/drivers/gl/driver.go:50 +0x20a

goroutine 1 [runnable, locked to thread]:
github.com/go-gl/glfw/v3.1/glfw.WaitEvents()
	/home/binet/tmp/go/src/github.com/go-gl/glfw/v3.1/glfw/window.go:641
github.com/google/gxui/drivers/gl.(*Driver).run(0xc20803a3c0)
	/home/binet/tmp/go/src/github.com/google/gxui/drivers/gl/driver.go:93 +0x81
github.com/google/gxui/drivers/gl.StartDriver(0x725070, 0x4, 0x7b2920)
	/home/binet/tmp/go/src/github.com/google/gxui/drivers/gl/driver.go:51 +0x21a
main.main()
	/home/binet/tmp/go/src/github.com/google/gxui/samples/progress_bar/main.go:52 +0x48

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
	/usr/lib/go/src/runtime/asm_amd64.s:2232 +0x1
exit status 2
```

could these files (or a recipe to get them) be included?

-s

**Comment by ryadzenine** [comment]
Hi there, here is the ressource you are looking for (Source Code Pro) [http://adobe-fonts.github.io/source-code-pro/]

**Comment by ben-clayton** [comment]
I've started the [os_fonts branch](https://github.com/google/gxui/tree/os_fonts) to search the OS's fonts directory so we can use Arial or something equally common as the default font.
I need to implement and test for Windows and Linux, which I'll try and do tomorrow.

**Comment by ajstarks** [comment]
you can run the samples like this:

    $ ./polygon -data ~/Downloads

if ~/Downloads contains SourceCodePro-Regular.ttf

**Comment by cnbuff410** [comment]
The one I downloaded from http://adobe-fonts.github.io/source-code-pro/ doesn't work. I have to download from online resource page(like [this one](http://www.1001freefonts.com/source_code_pro.font) to make it work. Just FYI.

**Comment by ben-clayton** [comment]
In e44108536, I've changed the default font to Arial.ttf and it now searches the OS font directories. In theory, you no longer need to download any fonts or set the `--data=` command line argument.
I've tested windows and OSX, hopefully Linux will also work.
Please re-open if you have issues.
