### ISSUE TITLE
unify font Draw and DrawRunes

### ISSUE THREAD

**Issue by crawshaw** [google/gxui#53]
I don't think the small allocation savings from supporting two code paths is worthwhile. It translates into a lot of API surface down the road.

But in trying to get rid of one, I discovered they work differently. LayoutRunes+DrawRunes produces different (seemingly incorrect) results compared to Draw. Is this on purpose, @ben-clayton? If not, I'll make LayoutRunes+DrawRunes behave like Draw now and remove Draw.

**Comment by ben-clayton** [comment]
Nope, they were written to behave similarly, but I can completely believe I've screwed up some of the logic - as you can see it's full of fiddly DIP -> pixel space conversion, ascent and alignment calculations.
I'm not opposed to killing Draw and keeping the more explicit APIs.

**Comment by ben-clayton** [comment]
I believe this to be fixed. Closing.
