### ISSUE TITLE
Custom Graphical Elements?

### ISSUE THREAD

**Issue by tones111** [google/gxui#55]
With the available graphical elements all created via the theme interface it seems that applications wanting/needing to provide custom elements will be difficult.  Is it possible for a client to design their own widget, add it to a layout, and have it rendered?  I haven't yet wrapped my head around the mixin architecture enough to determine if a compliant object just needs to meet a set of interfaces.  If it's possible, this might make for a good, simple example.

**Comment by ben-clayton** [comment]
> Is it possible for a client to design their own widget, add it to a layout, and have it rendered?

Yes, completely. There's really nothing special about the mixin implementations, but I completely understand that the whole structure is really confusing. We're thinking about how we can clean this lot up, and make it more idiomatic.

To very briefly describe the current layout:

* The top level is the theme. This is really just a factory for a number of control types that implement the interfaces in the GXUI root. The theme can tweak the control's colors and styling by changing fields and overriding some of methods of the mixins.
* The ```mixins``` directory holds full, un-styled implementations of the various controls. They usually 'derive' from one of the types in the ```base``` package.
* The ```mixins\base``` package provides the bulk of the implementation for ```Control``` and ```Container``` types. They are formed from pulling together a bunch of parts.
* The ```mixins\parts``` package holds partial implementations of controls. i.e. [```Layoutable```](https://github.com/google/gxui/blob/master/mixins/parts/layoutable.go) implements the ```SetMargin```, ```Margin```, ```Bounds```, ```Layout```, and ```Relayout``` methods the way *most* of controls would want. You can cherry-pick these parts into your new control to remove boilerplate code.

> If it's possible, this might make for a good, simple example.

I agree more samples are usually good, but I'm wary of giving examples at this stage for things that are very likely to significantly change. I don't think anyone is happy with the way Component are currently built (the whole mixin and Foo[Outer](https://github.com/google/gxui/blob/master/mixins/button.go#L13) stuff are like hammering a square-peg in a round hole). If we can sort this out, then I'm more than happy to create step-by-step tutorials.

If you'd like any more information on any of this, please ask away. The more information I can share, the higher chance there is that someone can offer a far better and cleaner approach to solve the same problems. :)
