### ISSUE TITLE
Run sample error on windows

### ISSUE THREAD

**Issue by justay** [google/gxui#67]
$ go run main.go
panic: Failed to initialize gl: glGetBufferParameteri64v

goroutine 1 [running, locked to thread]:
github.com/google/gxui/drivers/gl.CreateViewport(0xc08200a380, 0x320, 0x258, 0x7
537d0, 0x5, 0xc082023e88)
        C:/Go/src/github.com/google/gxui/drivers/gl/viewport.go:68 +0x2ab
github.com/google/gxui/drivers/gl.func路016()
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:142 +0x68
github.com/google/gxui/drivers/gl.func路011()
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:57 +0x36
github.com/google/gxui/drivers/gl.(*Driver).run(0xc08200a380)
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:85 +0x7c
github.com/google/gxui/drivers/gl.StartDriver(0x8fc090)
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:47 +0x1ec
main.main()
        E:/golang/app/UI/main.go:164 +0x31

goroutine 17 [syscall, locked to thread]:
runtime.goexit()
        c:/go/src/runtime/asm_amd64.s:2232 +0x1

goroutine 5 [chan receive]:
github.com/google/gxui/drivers/gl.(*Driver).syncDriver(0xc08200a380, 0xc08218cd2
0)
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:58 +0x137
github.com/google/gxui/drivers/gl.(*Driver).CreateViewport(0xc08200a380, 0x320,
0x258, 0x7537d0, 0x5, 0x0, 0x0)
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:147 +0x1e1
github.com/google/gxui/mixins.(*Window).Init(0xc08201b8c0, 0x3694f0, 0xc08201b8c
0, 0x361fd8, 0xc08200a380, 0x320, 0x258, 0x7537d0, 0x5)
        C:/Go/src/github.com/google/gxui/mixins/window.go:71 +0x326
github.com/google/gxui/themes/dark.CreateWindow(0xc08219e000, 0x320, 0x258, 0x75
37d0, 0x5, 0x0, 0x0)
        C:/Go/src/github.com/google/gxui/themes/dark/window.go:19 +0x119
github.com/google/gxui/themes/dark.(*Theme).CreateWindow(0xc08219e000, 0x320, 0x
258, 0x7537d0, 0x5, 0x0, 0x0)
        C:/Go/src/github.com/google/gxui/themes/dark/theme.go:169 +0x69
main.appMain(0x361fd8, 0xc08200a380)
        E:/golang/app/UI/main.go:155 +0x1de
created by github.com/google/gxui/drivers/gl.StartDriver
        C:/Go/src/github.com/google/gxui/drivers/gl/driver.go:46 +0x1dc
exit status 2

**Comment by ben-clayton** [comment]
What graphics card / drivers do you have installed?

**Comment by justay** [comment]
Intel(R) HD Graphics 3000 
drivers come for Intel and version is 9.17.10.3517

**Comment by sunwangme** [comment]
why gxui use opengl 3.2？the card just support 3.1

**Comment by shit386** [comment]
same problem.

how to solve it ?

**Comment by webmaster-gostec** [comment]
Same problem here, with a Intel Core i3 Sandy Bridge and integrated graphics card.
I think the problem is due to the fact our hardware supports OpenGL up to 3.1 while gxui requires OpenGL 3.2.

**Comment by sunwangme** [comment]
btw,#version 150 should add to glsl code, if we use use the future of opengl3.2/glsl1.5. or opgl3.1/glsl1.4

**Comment by ben-clayton** [comment]
I've dropped the GL version down to 2.1.
Hopefully this is enough for your drivers / cards.

**Comment by shit386** [comment]
it's working now.
