### ISSUE TITLE
Scaling not supported (at least when running samples on Windows 8.1)

### ISSUE THREAD

**Issue by tompccs** [google/gxui#68]
Scaling is not supported by default on Windows 8.1 using the samples. UI elements appear tiny and fonts are nearly unreadable. 

Tested on a Dell XPS 13 2015 with QHD display

**Comment by ben-clayton** [comment]
GXUI does support scaling - on OSX 'retina' screens we will bump the resolution, but keep the physical size the same. All units external to the driver are in DIPs.
My guess is that GLFW is not reporting the window as high DPI.

**Comment by ben-clayton** [comment]
I can't really help what GLFW / windows is telling us to display, but I've added a manual scale override with b655aa1.
Use the new ```--scaling``` command line flag to change the display scaling. For example:

cd %GOPATH%
go run src\github.com\google\gxui\samples\tree\main.go --scaling=2
