### ISSUE TITLE
drivers/gl/refcounted.go: data race on refCount field

### ISSUE THREAD

**Issue by cookieo9** [google/gxui#69]
In drivers/gl/refcounted.go, the refCount field is updated using atomic.AddUint32 properly, but is not read using atomic.LoadUint32, so data races can still occur (at least according to the race detector...).

For example, there is a non-atomic read resulting in a data race detected at https://github.com/google/gxui/blob/master/drivers/gl/refcounted.go#L62

**Comment by ben-clayton** [comment]
Thanks for reporting this. Fixed.
