### ISSUE TITLE
Incorrect tree searching with collapsed nodes

### ISSUE THREAD

**Issue by tones111** [google/gxui#80]
It appears the tree node search algorithm doesn't work when attempting to search down a collapsed node.

To reproduce:
Add a fmt.Println statement in samples/file_dlg/main.go immediately before the directories.Show(path) line in the enter key handler.
build and run the file_dlg sample application
find a collapsed node and edit the fullpath text box to that path plus some additional directory name that doesn't exist (ex: /home/username/junk)
Notice that the printout is displayed, indicating that directories.Select returned true

This contradicts the tree.go Select documentation in two ways:
1. Select is supposed to return false when the tree does not contain the specified item
2. The tree's appearance is modified during the Select with the collapsed directory now expanded.

Note that entering an invalid path from an expanded node appears to work correctly (no print out and the tree's appearance is unchanged).

**Comment by ben-clayton** [comment]
This is completely WAI.

```go
	// Select makes the specified item selected. The tree will not automatically
	// expand to the newly selected item. If the Tree does not contain the
	// specified item, then Select returns false and the previous selection
	// remains unaltered.
```

> This contradicts the tree.go Select documentation in two ways:
> 1. Select is supposed to return false when the tree does not contain the specified item

The tree does contain the item, in this case it is just not visible as one of the ancestors has not been expanded.

> 2. The tree's appearance is modified during the Select... 

There's nothing in the documentation that says that the appearance won't change. The appearance has changed to indicate that one of the non-visible children is selected. This is the same as selecting a leaf node, then collapsing its parent.

> with the collapsed directory now expanded.

The expansion is not done with select, it's done with [Show](https://github.com/google/gxui/blob/master/tree.go#L22). Are you saying that when you comment out [this line](https://github.com/google/gxui/blob/master/samples/file_dlg/main.go#L211) the tree still expands?

**Comment by ben-clayton** [comment]
Sorry, I replied just after waking up. Now that I've been awake long enough to have my brain work, I've actually understood what you said. This does indeed sound broken. I'll take a look.
