### ISSUE TITLE
Unsupport global language

### ISSUE THREAD

**Issue by justay** [google/gxui#85]
when change the language, captions display error. and It happens on textbox too.

![qq 20150330222530](https://cloud.githubusercontent.com/assets/7291805/6898690/28014424-d72e-11e4-9965-468e35a6dcc9.png)

**Comment by ben-clayton** [comment]
It looks like the default font [Roboto-Regular.ttf](https://github.com/google/fonts/raw/master/apache/roboto/Roboto-Regular.ttf) does not contain the glyphs you are trying to use.
Please try loading a true-type font you know to contain your language glyphs and pass this to [Driver.CreateFont](https://github.com/google/gxui/blob/master/driver.go#L24).
Please reopen if this does not work for you.
