### ISSUE TITLE
Setting size mode to "Fill" pushes other controls off screen

### ISSUE THREAD

**Issue by tones111** [google/gxui#92]
The following example illustrates how setting a linear layout's size mode to fill prevents later controls from being drawn (the fill pushes them off the window).

package main

import (
	"github.com/google/gxui"
	"github.com/google/gxui/drivers/gl"
	"github.com/google/gxui/themes/dark"
)

func appMain(driver gxui.Driver) {
	theme := dark.CreateTheme(driver)
	var label gxui.Label

	topRow := theme.CreateLinearLayout()
	topRow.SetDirection(gxui.LeftToRight)
	label = theme.CreateLabel()
	label.SetText("A")
	topRow.AddChild(label)
	label = theme.CreateLabel()
	label.SetText("B")
	topRow.AddChild(label)
	label = theme.CreateLabel()
	label.SetText("C")
	topRow.AddChild(label)

	main := theme.CreateLinearLayout()
	main.SetDirection(gxui.TopToBottom)
	main.SetSizeMode(gxui.Fill)
	label = theme.CreateLabel()
	label.SetText("main")
	main.AddChild(label)

	bottomRow := theme.CreateLinearLayout()
	bottomRow.SetDirection(gxui.LeftToRight)
	label = theme.CreateLabel()
	label.SetText("1")
	bottomRow.AddChild(label)
	label = theme.CreateLabel()
	label.SetText("2")
	bottomRow.AddChild(label)
	label = theme.CreateLabel()
	label.SetText("3")
	bottomRow.AddChild(label)

	window := theme.CreateWindow(200, 200, "Sample")

	layout := theme.CreateLinearLayout()
	layout.SetDirection(gxui.TopToBottom)
	layout.AddChild(topRow)
	layout.AddChild(main)
	layout.AddChild(bottomRow)

	window.AddChild(layout)
	window.OnClose(driver.Terminate)
}

func main() {
	gl.StartDriver(appMain)
}

**Comment by ben-clayton** [comment]
This is WAI - I'm curious to know what you'd expect the behavior to be in this case.
I'll try making time to properly document the ```LinearLayout``` interface today.

**Comment by ben-clayton** [comment]
BTW - what you're probably trying to accomplish can probably be done with:
```go
   b2t := theme.CreateLinearLayout()
   b2t.SetDirection(gxui.BottomToTop)
   b2t.AddChild(bottomRow)
   b2t.AddChild(main)

   t2b := theme.CreateLinearLayout()
   t2b.SetDirection(gxui.TopToBottom)
   t2b.AddChild(topRow)
   t2b.AddChild(b2t)
```

although I have not tested this...

**Comment by ben-clayton** [comment]
First pass documentation in 62c937dba870ed541250c6001a59e4b1903bd4c5.
Please reopen if this still doesn't work for you, or is still unclear.

**Comment by tones111** [comment]
Aha, I see what you did there in your sample.  Thanks for the docs, that helps clarify some of the corner cases I'd been experimenting with.  I'm looking forward to devising / helping support more advanced layouts but understand there's higher priority work to be done in the meantime.  Thanks for the suggestion above.
